# Generated by Django 5.2.15 on 2026-06-18 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='clock_in',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='clock_out',
            new_name='check_out',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='attendance_status',
            new_name='status',
        ),
    ]
