# Generated by Django 5.2.15 on 2026-06-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Archived', 'Archived'), ('Deleted', 'Deleted'), ('Pending Verification', 'Pending Verification'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending Verification', max_length=30),
        ),
    ]
