# Generated by Django 5.2.15 on 2026-06-17 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_month', models.IntegerField()),
                ('payroll_year', models.IntegerField()),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_allowances', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('provident_fund', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Processed', 'Processed'), ('Paid', 'Paid')], default='Draft', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='employees.employee')),
            ],
            options={
                'unique_together': {('employee', 'payroll_month', 'payroll_year')},
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payslip_number', models.CharField(max_length=50, unique=True)),
                ('pdf_file', models.CharField(blank=True, max_length=300, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('payroll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payslip', to='payroll.payroll')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('house_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('provident_fund_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='employees.employee')),
            ],
        ),
    ]
