# Generated by Django 5.2.15 on 2026-06-19 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_deleted_at_employee_is_active_and_more'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salarystructure',
            unique_together={('employee',)},
        ),
    ]
