# Generated by Django 5.2.15 on 2026-06-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interview_round',
            field=models.CharField(choices=[('HR Screening', 'HR Screening'), ('Technical Round', 'Technical Round'), ('Manager Round', 'Manager Round'), ('Final Round', 'Final Round')], default='HR Screening', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Screening', 'Screening'), ('Shortlisted', 'Shortlisted'), ('Interview Scheduled', 'Interview Scheduled'), ('Interview Completed', 'Interview Completed'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Applied', max_length=30),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Open', 'Open'), ('Closed', 'Closed'), ('On Hold', 'On Hold')], default='Open', max_length=20),
        ),
    ]
